# Be More Cyberaware

In [1]:
import zipfile 

with zipfile.ZipFile('archive.zip', 'r') as zip_ref:
    zip_ref.extractall('extracted_files')

In [22]:
import pandas as pd

df = pd.read_excel('extracted_files/Cyber_Awareness_Survey.xlsx')

In [ ]:
# Count totals of each column and map yes to 1 and no to 0
p_change_agg = df["Do you change your password Frequently?"].map({1:"Yes", 0:"No"}).value_counts()

# Count totals of cyber awareness and map yes to 1 and no to 0
cyber_aware_agg = df["Are you aware of cyber laws?!"].map({1:"Yes", 0:"No"}).value_counts()

# Count totals of how frequent the password is changed
p_change_freq = df["How Frequent!?"].value_counts()

# Count totals of social media usage for each distinct amount of time
social_media_counts = df["Social Media Usage (in Hours)"].value_counts()

# Count the totals for each social media platform
top_social_media = df["Preferred Social Media 1"].value_counts()

# Create a cross table of how frequent password is changed and if the individual thinks they change the password frequently
corr_freq_chg = pd.crosstab(
    df["Do you change your password Frequently?"].map({1:"Yes", 0:"No"}),
    df["How Frequent!?"]
)

In [ ]:
def weighted_ranking(df):
    """Calculates a weighted ranking of each platform based on the preference each person put the application as

    Args:
        df (pd.DataFrame): A dataframe with the columns "Preferred Social Media 1", "Preferred Social Media 2", "Preferred Social Media 3", and "Preferred Social Media 4"

    Returns:
        pd.DataFrame: A dataframe with the platforms and their weighted score sorted in descending order
    """
    weights = {
        "Preferred Social Media 1": 4,
        "Preferred Social Media 2": 3,
        "Preferred Social Media 3": 2,
        "Preferred Social Media 4": 1
    }

    scores = {}

    # Loops over each column and its weight
    for col, weight in weights.items():
        # Loops through all platforms in that column
        for row_platform in df[col]:
            # Makes a dictionary of platforms and gets the score for the platform defaulting to 0 and then adds the weight
            scores[row_platform] = scores.get(row_platform, 0) + weight

    weighted_ranking = (
        pd.DataFrame(scores.items(), columns=["Social Media", "Weighted Score"])
        .sort_values("Weighted Score", ascending=False)
    )

    return weighted_ranking

In [19]:
pd.crosstab(
    df["Preferred Social Media 1"],
    df["Social Media Usage (in Hours)"]
)

Social Media Usage (in Hours),1 hrs / day,3 hrs / day,4 hrs / day,> 5 hrs / day
Preferred Social Media 1,,,,
Facebook,2,4,2,0
Instagram,64,86,32,17
LinkedIn,9,6,1,1
Twitter,6,4,0,2

In [21]:
pd.crosstab(
    df["Do you post personal pictures, share important events of your life in Social Media including Messenger Apps?"].map({2:"Post personal pictures and share important events",1:"Post just personal pictures", 0:"None"}),
    df["Social Media Usage (in Hours)"]
)

Social Media Usage (in Hours),1 hrs / day,3 hrs / day,4 hrs / day,> 5 hrs / day
"Do you post personal pictures, share important events of your life in Social Media including Messenger Apps?",,,,
None,35,25,6,6
Post just personal pictures,17,36,14,6
Post personal pictures and share important events,29,39,15,8